# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy Personal Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js to build repo ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --legacy-peer-deps
    - run: npm run build --if-present
    - name: SFTP Deploy to dev.emgenbro.net
      uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: true # optional
        host: ${{ secrets.DEV_ENV_HOST }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
        port: 22 # optional, default is: 21
        username: ${{ secrets.DEV_ENV_USERNAME }} # FTP username
        password: ${{ secrets.DEV_ENV_PASSWORD }} # FTP password
        remote_folder: dev.emgenbro.net # optional, remote path of your FTP server
        local_folder: dist/ # optional, local path, default is: dist
        cleanup: false # optional, remove existing files inside FTP remote folder
        pasive: true # optional
